#ifndef PROGRAM_DEFINES_H 
#define PROGRAM_DEFINES_H 

typedef enum{ 
INIT,
RUN_ONCE,
READ_TV_COMMAND,
WAKE_SERVER,
WAKE_TV,
RESET_IR_COMMAND,
ERROR,
}CODE_STATUS_ENUM; 

typedef enum{ 
READ_TV_COMMAND_SUCCESS,
READ_TV_COMMAND_ERROR,
WAKE_SERVER_SUCCESS,
WAKE_TV_SUCCESS,
HANDLED,
}RETURN_ERROR_STATUS;

typedef enum{ 
TV_COMMAND_FOUND,
TV_COMMAND_NOT_FOUND,
}IR_COMMAND_STATUS_ENUM; 
#endif