on: [push]
jobs: 
  build:
      runs-on: ubuntu-latest
      container:
        image: onizuka09/starter-container:v1.0
      steps:
        - name: Checkout the repository 
          uses: actions/checkout@v3
          with:
            submodules: true
        - name: Build firmware 
          run: make build 

